name: Test Docker Image

on:
    workflow_dispatch:
    # push:
    #     branches: [ main ]
    #     paths:
    #     - 'app.py'
    #     - 'Dockerfile'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.AUTH }}

    - name: Pull Docker image from GitHub Container Registry
      run: docker pull ghcr.io/nikgapps/docker:latest

    - name: Run the Docker container
      run: docker run --rm ghcr.io/nikgapps/docker:latest
