name: Build and Push Docker Image

on:
    workflow_dispatch:
    push:
        branches:
        - main  # Trigger the workflow on push events to the 'main' branch
        paths:
        - '**.py'
        - 'requirements.txt'
        - 'Dockerfile'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: docker
  IMAGE_TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.AUTH }}
    
    - name: Extract Docker Meta Data
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
      
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max
  test:
    runs-on: ubuntu-latest

    needs: build-and-push

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.AUTH }}

    - name: Pull latest Docker image
      run: docker pull ghcr.io/nikgapps/docker:latest

    - name: Run Docker image with Git config and script execution
      run: |
        docker run --rm \
        ghcr.io/nikgapps/docker:latest \
        "${{ secrets.GIT_USER_NAME }}" "${{ secrets.GIT_USER_EMAIL }}" "${{ github.event.inputs.android_version }}" "${{ github.event.inputs.package_list }}"
  