name: Run Docker Image

on:
    workflow_dispatch:

jobs:
  run-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Pull latest Docker image
      run: docker pull ghcr.io/nikgapps/docker:latest
      
    - name: Run Docker image
      run: docker run --rm ghcr.io/nikgapps/docker:latest 13 core,basic
